# Generated by Django 5.0.4 on 2024-05-09 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JackConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='JackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('response', models.CharField(max_length=10000)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jack.jackconversation')),
            ],
        ),
    ]
