# Generated by Django 5.0.4 on 2024-05-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackquestion',
            old_name='response',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='jackquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='jackquestion',
            name='isAi',
            field=models.BooleanField(default=False),
        ),
    ]
