# Generated by Django 5.0.4 on 2024-05-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0002_rename_response_jackquestion_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jackquestion',
            old_name='message',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='jackquestion',
            name='isAi',
        ),
        migrations.AddField(
            model_name='jackquestion',
            name='question',
            field=models.CharField(default='hola', max_length=400),
            preserve_default=False,
        ),
    ]
