# Generated by Django 3.2.25 on 2024-04-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='created_by',
            new_name='created',
        ),
    ]
