# Generated by Django 3.2.25 on 2024-04-29 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('diets', '0003_rename_created_meal_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='client.nutritionist'),
            preserve_default=False,
        ),
    ]
