# Generated by Django 5.0.2 on 2024-03-03 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('diets', '0003_ingredients_remove_meal_ingredients_meal_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='created_by',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='client.nutritionist'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MealToClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('meal', models.ManyToManyField(to='diets.meal')),
            ],
        ),
    ]
