# Generated by Django 5.0.2 on 2024-03-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_meal_created_by_mealtoclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MealToClient',
        ),
    ]
