# Generated by Django 3.2.25 on 2024-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_ingredients_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='data',
            field=models.JSONField(default=0),
        ),
    ]
