# Generated by Django 5.0.2 on 2024-03-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_remove_meal_created_by_delete_mealtoclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
