# Generated by Django 5.0.4 on 2024-05-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('diets', '0005_ingredients_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('D', 'desayuno'), ('A', 'almuerzo'), ('C', 'cena')], max_length=4)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('ingredients', models.ManyToManyField(blank=True, to='diets.ingredients')),
            ],
        ),
    ]
