# Generated by Django 5.0.2 on 2024-03-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('diets', '0006_delete_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='client.nutritionist')),
                ('ingredients', models.ManyToManyField(to='diets.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='MealToClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('meal', models.ManyToManyField(to='diets.meal')),
            ],
        ),
    ]
