# Generated by Django 5.0.2 on 2024-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_mealtoclient_meal_time_alter_meal_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtoclient',
            name='meal_time',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
