# Generated by Django 5.0.2 on 2024-03-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0010_alter_ingredients_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='meal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='diets.meal'),
        ),
        migrations.RemoveField(
            model_name='mealtoclient',
            name='meal',
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meals', models.ManyToManyField(to='diets.meal')),
            ],
        ),
        migrations.AddField(
            model_name='mealtoclient',
            name='meal',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diets.dailymeal'),
            preserve_default=False,
        ),
    ]
