# Generated by Django 5.0.2 on 2024-03-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0011_remove_meal_ingredients_ingredients_meal_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='meal_id',
        ),
    ]
